### ISSUE TITLE
Addressable::URI::InvalidURIError: Invalid scheme format.

### ISSUE THREAD

**Issue by rmontgomery429** [oscardelben/firebase-ruby#47] opened 2015-10-05 16:01 UTC
I'm running into an issue when creating a new instance of `Firebase` with our Firebase URL. I see that the `addressable` gem has had reported issues (https://github.com/bblimke/webmock/issues/489) with this but I'm not sure if anyone has run into this before. Even the example from the README returns this same error.

The example below I ran in rails console. Ruby 2.2.2, Rails 4.1.5, firebase-ruby 0.2.4.

```
base_uri = 'https://foobarbaz.firebaseio.com/'
firebase = Firebase::Client.new(base_uri)

Addressable::URI::InvalidURIError: Invalid scheme format.
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/addressable-2.3.6/lib/addressable/uri.rb:864:in `scheme='
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/addressable-2.3.6/lib/addressable/uri.rb:794:in `block in initialize'
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/addressable-2.3.6/lib/addressable/uri.rb:2238:in `call'
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/addressable-2.3.6/lib/addressable/uri.rb:2238:in `defer_validation'
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/addressable-2.3.6/lib/addressable/uri.rb:791:in `initialize'
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/addressable-2.3.6/lib/addressable/uri.rb:134:in `new'
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/addressable-2.3.6/lib/addressable/uri.rb:134:in `parse'
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/httpclient-2.4.0/lib/httpclient/util.rb:132:in `urify'
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/httpclient-2.4.0/lib/httpclient.rb:451:in `proxy='
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/httpclient-2.4.0/lib/httpclient.rb:397:in `initialize'
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/firebase-0.2.4/lib/firebase/request.rb:7:in `new'
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/firebase-0.2.4/lib/firebase/request.rb:7:in `initialize'
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/firebase-0.2.4/lib/firebase.rb:15:in `new'
  from /Users/rmontgomery429/.rvm/gems/ruby-2.2.2/gems/firebase-0.2.4/lib/firebase.rb:15:in `initialize'
  from (irb):8:in `new'
```

Am I doing it wrong? What am I missing here?

**Comment by vincentwoo** [comment] 2015-10-09 12:07
I'm having trouble reproducing:

```
vwoo$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

vwoo$ gem list firebase

*** LOCAL GEMS ***

firebase (0.2.4)

vwoo$ irb
irb(main):001:0> require 'firebase'
=> true
irb(main):002:0> base_uri = 'https://foobarbaz.firebaseio.com/'
=> "https://foobarbaz.firebaseio.com/"
irb(main):003:0> firebase = Firebase::Client.new(base_uri)
=> #<Firebase::Client:0x007f84619d75a0 ...>
```

Is there anything specific about your environment that might be causing this? Does this error always happen? If so, can you isolate what causes it?

**Comment by vincentwoo** [comment] 2015-10-09 12:10
Ah, actually, it seems like `httpclient` tries to use `addressable` if it is installed: https://github.com/nahi/httpclient/blob/master/CHANGELOG.md#changes-in-230.

If this is an `addressable` issue, is the problem fixed in a more recent release? If so, can you upgrade to it? If not, can you file an issue there, too?

**Comment by vincentwoo** [comment] 2015-11-19 13:49
closing due to inactivity, reopen if it was more of an issue than just upgrading `addressable`

**Closed by vincentwoo** 2015-11-19 13:49 UTC

**Comment by Emeritus-androiddev1** [comment] 2016-03-03 06:47
I am also getting the same issues

**Comment by vincentwoo** [comment] 2016-03-03 06:56
What version of `addressable` are you using?

**Comment by idanelor** [comment] 2016-05-30 06:41
It reproduces for me as well. In both addressable 2.4.0 and 2.3.8.
In WebMock framework (request_pattern.rb): WebMock::Util::URI.variations_of_uri_as_strings(uri) generates several variations that some of them does not include scheme (i.e. 127.0.0.1/bla_bla) and then the addressable parser crashes. Any workaround for this until it is fixed?

**Comment by peach-adrian** [comment] 2016-06-30 16:46
You need use ruby 2.2.3, this work for me and use the last version for addressable 2.4.0.

**Comment by idanelor** [comment] 2016-07-06 10:17
I'm using addressable 2.4.0 and ruby 2.3.0 .. any suggestions if I can't downgrade my ruby version (and i'm not sure it will solve it since it reproduced in older version as well of ruby)

**Comment by vincentwoo** [comment] 2016-07-06 21:36
using ruby 2.3.1 and

```
addressable (2.4.0)
firebase (0.2.6)
```

I do not have this issue. Is there a minimally reproducible app or repo you can push? Can you cause this to happen on other machines?

**Comment by fabioaraujo121** [comment] 2019-03-29 15:24
I'm getting a similar error when I try to send to a specific fcm id.

`Addressable::URI::InvalidURIError (Invalid scheme format: eDgI_h5hrRw)`

```
class Notification
	attr_reader :firebase
	BASE_URI = 'https://rade-1234.firebaseio.com/'

	def initialize(obj = {})
		private_key_json_string = File.open("#{Rails.root}/lib/fcm/rade-1234-firebase-adminsdk-6xsyo-fd06cf9dff.json").read
		@firebase = Firebase::Client.new(BASE_URI, private_key_json_string)
	end

	def send(user, message={})
		self.firebase.push(user.fcm_id, message)
	end
end
```

But, when I send, like the smaple, to "todos" it goes fine...

I believe I made some mistake when try send to a specific user. How do I do that?
